workflows:
  android-debug:
    name: Android Debug APK
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Prepare Flutter Android project
        script: |
          echo "Working dir: $(pwd)"
          # Create Android project if missing
          if [ ! -d "android" ]; then
            flutter create . --platforms=android
          fi

          # Ensure AndroidX/Jetifier and Gradle/Kotlin memory
          echo "org.gradle.jvmargs=-Xmx3g -Dkotlin.daemon.jvm.options=-Xmx1g" >> android/gradle.properties
          echo "android.useAndroidX=true" >> android/gradle.properties
          echo "android.enableJetifier=true" >> android/gradle.properties

          # Force safe SDK versions for ML Kit & plugins
          APP_GRADLE="android/app/build.gradle"
          if [ -f "$APP_GRADLE" ]; then
            # compileSdkVersion 34
            sed -i.bak 's/compileSdkVersion [0-9][0-9]*/compileSdkVersion 34/g' "$APP_GRADLE" || true
            # targetSdkVersion 34 & minSdkVersion 21
            sed -i.bak 's/minSdkVersion [0-9][0-9]*/minSdkVersion 21/g' "$APP_GRADLE" || true
            sed -i.bak 's/targetSdkVersion [0-9][0-9]*/targetSdkVersion 34/g' "$APP_GRADLE" || true
          fi

          # Add required permissions if not present
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          if [ -f "$MANIFEST" ]; then
            if ! grep -q 'android.permission.CAMERA' "$MANIFEST"; then
              sed -i.bak 's#<application#<uses-permission android:name="android.permission.CAMERA"/>\
<uses-permission android:name="android.permission.RECORD_AUDIO"/>\
<uses-permission android:name="android.permission.WAKE_LOCK"/>\
\
<application#' "$MANIFEST"
            fi
          fi

          flutter clean
          flutter pub get

      - name: Diagnostics (helps catch the real error)
        script: |
          flutter --version
          flutter doctor -v
          echo "---- android/gradle.properties ----"
          cat android/gradle.properties || true
          echo "---- android/app/build.gradle (sdk lines) ----"
          grep -nE 'compileSdkVersion|minSdkVersion|targetSdkVersion' android/app/build.gradle || true

      - name: Build (Gradle with stacktrace)
        script: |
          cd android
          ./gradlew assembleDebug --no-daemon --stacktrace --info

    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
