workflows:
  android-debug:
    name: Android Debug APK
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Prepare Flutter Android project
        script: |
          echo "Working dir: $(pwd)"
          # 1) Create Android project if missing
          if [ ! -d "android" ]; then
            flutter create . --platforms=android
          fi

          # 2) AndroidX + Gradle/Kotlin memory
          {
            echo "org.gradle.jvmargs=-Xmx3g -Dkotlin.daemon.jvm.options=-Xmx1g"
            echo "android.useAndroidX=true"
            echo "android.enableJetifier=true"
          } >> android/gradle.properties

          # 3) Force safe SDK versions for ML Kit & plugins
          APP_GRADLE="android/app/build.gradle"
          if [ -f "$APP_GRADLE" ]; then
            sed -i.bak 's/compileSdkVersion [0-9][0-9]*/compileSdkVersion 34/g' "$APP_GRADLE" || true
            sed -i.bak 's/minSdkVersion [0-9][0-9]*/minSdkVersion 21/g' "$APP_GRADLE" || true
            sed -i.bak 's/targetSdkVersion [0-9][0-9]*/targetSdkVersion 34/g' "$APP_GRADLE" || true
          fi

          # 4) Add required permissions to AndroidManifest.xml (safe Python edit)
          python3 - <<'PY'
import io, os, sys
p = "android/app/src/main/AndroidManifest.xml"
if os.path.exists(p):
    txt = io.open(p, "r", encoding="utf-8").read()
    if "android.permission.CAMERA" not in txt:
        txt = txt.replace(
            "<application",
            '<uses-permission android:name="android.permission.CAMERA"/>\n'
            '<uses-permission android:name="android.permission.RECORD_AUDIO"/>\n'
            '<uses-permission android:name="android.permission.WAKE_LOCK"/>\n\n'
            "<application"
        )
        io.open(p, "w", encoding="utf-8").write(txt)
PY

          flutter clean
          flutter pub get

      - name: Diagnostics (helps catch the real error)
        script: |
          flutter --version
          flutter doctor -v
          echo "---- android/gradle.properties ----"
          cat android/gradle.properties || true
          echo "---- android/app/build.gradle (sdk lines) ----"
          grep -nE 'compileSdkVersion|minSdkVersion|targetSdkVersion' android/app/build.gradle || true

      - name: Build (Gradle with stacktrace)
        script: |
          cd android
          ./gradlew assembleDebug --no-daemon --stacktrace --info

    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
