name: opticia_full
description: Full version of Opticia — Eye-gaze cursor with face auth, calibration, and settings
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0
  google_mlkit_face_detection: ^0.11.0
  permission_handler: ^11.3.0
  shared_preferences: ^2.3.2
  audioplayers: ^6.0.0

flutter:
  uses-material-design: true
