- name: Download OpenCV cascades into assets
  run: |
    mkdir -p assets/haarcascades
    curl -L -o assets/haarcascades/haarcascade_frontalface_default.xml https://raw.githubusercontent.com/opencv/opencv/4.x/data/haarcascades/haarcascade_frontalface_default.xml
    curl -L -o assets/haarcascades/haarcascade_eye_tree_eyeglasses.xml https://raw.githubusercontent.com/opencv/opencv/4.x/data/haarcascades/haarcascade_eye_tree_eyeglasses.xml
